name: Paper-Kotlin-Template
version: 1.0.0
main: gg.flyte.template.PluginTemplate
api-version: '1.20'
authors: [ The Flyte Team ]
description: Paper Plugin Template written in Kotlin.
website: https://flyte.gg